name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      LLM_MODEL: gemini-2.5-pro
      LLM_ENABLE_REMOTE: "false"  # avoid network calls in CI
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install deps
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Lint (ruff)
        run: poetry run ruff check .
      - name: Type check (mypy)
        run: poetry run mypy src
      - name: Tests (pytest)
        run: poetry run pytest -q
